--- /home/cameron/Documents/linux-4.1.13/arch/arm/kernel/Makefile	2015-11-13 13:46:22.000000000 -0600
+++ arch/arm/kernel/Makefile	2016-01-24 19:08:07.944177338 -0600
@@ -18,7 +18,9 @@ CFLAGS_REMOVE_return_address.o = -pg
 obj-y		:= elf.o entry-common.o irq.o opcodes.o \
 		   process.o ptrace.o reboot.o return_address.o \
 		   setup.o signal.o sigreturn_codes.o \
-		   stacktrace.o sys_arm.o time.o traps.o
+		   stacktrace.o sys_arm.o time.o traps.o \
+                   sys_badcall.o sys_printlog.o
+
 
 obj-$(CONFIG_ATAGS)		+= atags_parse.o
 obj-$(CONFIG_ATAGS_PROC)	+= atags_proc.o
